<?php
use App\Helpers\BaseSeed;

/**
 * Tags seed.
 */
class TagsSeed extends BaseSeed
{
    public $limit = 500;

    /**
     * @return string table name for seed
     */
    public function getTableName()
    {
        // TODO: Implement getTableName() method.
        return "tags";
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $data = [];
        $articles = $this->fetchAll("Select id from articles");
        $tags = $this->fetchAll("Select id from tags");

        foreach ($articles as $article){

            foreach (array_slice($tags, 0, 5) as $tag){
                $data[] = [
                    'article_id'=>$article['id'],
                    'tag_id'=>$tag['id']
                ];
                array_shift($tags);
            }
        }


        $this->table('articles_tags')->insert($data)->save();

    }

    /**
     * @return array item for seed
     */
    public function getSeedItem()
    {
        return [
            'name'=> $this->getSeeder()->name
        ];
    }
}
